[project]
name = "jarvis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sreeshanth", email = "sreeshanthkprakash@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "groq>=1.7.0",
    "pillow>=12.3.0",
    "pyautogui>=0.9.54",
    "pyperclip>=1.11.0",
    "pytesseract>=0.3.13",
    "python-dotenv>=1.2.4",
    "pywin32>=312",
]

[project.scripts]
jarvis = "jarvis:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
